apiVersion: v1
kind: Secret
metadata:
  name: yandex-auth-config
  namespace: wili
type: Opaque
data:
  YANDEX_CLIENT_ID: YANDEX_CLIENT_ID_PLACEHOLDER
  YANDEX_CLIENT_SECRET: YANDEX_CLIENT_SECRET_PLACEHOLDER
